import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "@/styles/globals.css";

import { Navbar } from "@/components/layout/navbar";

import { cn } from "@/lib/utils";

const inter = Inter_Tight({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={cn(inter.className, "min-h-screen antialiased")}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
